In [69]:
import pandas as pd
import numpy as np
em_est = pd.read_csv('../result/action_estimation.csv')

em_list = [1,0,0,0,0,0]
# 분노 , 두려움 , 행복 , 슬픔 , 에너지, 우울

In [70]:
em_est

감정       에너지        회복        순환        정화
0   행복  0.324557  0.344684  0.257535  0.372669
1   우울  0.256301  0.539817  0.321080  0.273804
2   슬픔  0.310976  0.308342  0.262105  0.256712
3   열정  0.269738  0.488793  0.353732  0.360805
4   분노  0.322202  0.440319  0.408658  0.398532
5  두려움  0.295698  0.295809  0.393288  0.315617

In [83]:
def get_item_est(em_list):
#def get_item_est(self , em_list):
    item_est = np.array([0,0,0,0])
    for em in range(0,len(em_list)):                  
        item_est = item_est + (em_est.iloc[em][1:]) * em_list[em]
        #item_est = item_est + (self.em_est.iloc[em][1:]) * em_list[em]
        
    
    # add Normalization code
    # item_est를 적절히 Normailztion 하면 됨
    return np.array(item_est.tolist())

In [84]:
get_item_est(em_list)

array([0.32455681, 0.34468368, 0.2575352 , 0.37266921])

In [ ]:
# class 안에 넣을 함수
def get_item_est(self , em_list):
    item_est = np.array([0,0,0,0])
    for em in range(0,len(em_list)):                  
        item_est = item_est + (self.emothon_df[em][1:]) * em_list[em]
        
    # add Normalization code
    # item_est를 적절히 Normailztion 하면 됨
    return np.array(item_est.tolist())

# Test Section

In [85]:
em_list = [0,0,0,0,0,0]
get_item_est(em_list)

array([0., 0., 0., 0.])

In [86]:
em_list = [1,0,0,0,0,0]
print(get_item_est(em_list))
print(em_est.iloc[0].to_numpy()[1:])

[0.32455681 0.34468368 0.2575352  0.37266921]
[0.3245568096637726 0.3446836769580841 0.2575351953506469
 0.3726692140102386]


In [90]:
em_list = [1,1,1,1,1,1]
print(get_item_est(em_list))
print(sum(em_est['에너지']))
print(sum(em_est['회복']))
print(sum(em_est['순환']))
print(sum(em_est['정화']))

[1.77947111 2.4177636  1.99639751 1.97813998]
1.7794711142778394
2.4177635967731477
1.9963975131511686
1.9781399756669997
